// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"database/sql"
	"time"
)

type MedicationOrder struct {
	FileNumber      int64
	NurseName       sql.NullString
	Ward            sql.NullString
	Bed             sql.NullString
	Medication      sql.NullString
	Uom             sql.NullString
	RequestTime     time.Time
	NurseRemarks    sql.NullString
	Status          string
	PharmacyRemarks sql.NullString
}
