// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package database

import (
	"context"
	"database/sql"
)

const registerUser = `-- name: RegisterUser :one
INSERT INTO users (
        id,
        created_at,
        updated_at,
        username,
        hashed_password,
        ward,
        permission,
        first_name,
        last_name
    )
VALUES (gen_random_uuid(), NOW(), NOW(), $1, $2, $3, $4, $5, $6)
RETURNING id, username, hashed_password, ward, permission, created_at, updated_at, first_name, last_name
`

type RegisterUserParams struct {
	Username       string
	HashedPassword string
	Ward           string
	Permission     string
	FirstName      sql.NullString
	LastName       sql.NullString
}

func (q *Queries) RegisterUser(ctx context.Context, arg RegisterUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, registerUser,
		arg.Username,
		arg.HashedPassword,
		arg.Ward,
		arg.Permission,
		arg.FirstName,
		arg.LastName,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.HashedPassword,
		&i.Ward,
		&i.Permission,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FirstName,
		&i.LastName,
	)
	return i, err
}
